### ISSUE TITLE
Feedback - Skilopay

### ISSUE THREAD

**Issue by ssscassio** [neto15cg/trends-github#1]
Bom dia Eliezer!

Segue um breve Feedback sobre seu desafio, considere tudo como sugestões, se discordar de algo ou ficar com alguma dúvida estou disponível para discutirmos sobre.

**Review Geral:**

- Não consegui instalar o app seguindo os passos de instalação (SO: MacOs)
- Bom Readme, senti falta de um preview(screenshots ou gif) do app no android ou no iOS, não consegui executar seu app, então não consegui avaliar a interface.
- Utilização do typescript. (Diferencial)
- Código bem escrito, formatado e com poucos erros de digitação (Trenddings, conainer )
- Sugestão: Criar um arquivo de configurações para manter as cores padrões do app facilitaria o desenvolvimento e possíveis alterações de design sem ter que alterar cada arquivo ou tentar lembrar onde deve alterar.
- Na tela **Details** poderia ter trabalhado melhor com a tipagem a fim de especificar qual o formato do parâmetro `repository` usando o NavigationParams do react-navigation. 
- Evite o uso de tipagem com `any` (ex: Favorites/index.tsx ::17,35),  principalmente se você pretende utilizar objetos vindos direto da api, esse tipo não lhe entrega nenhuma vantagem de _intellisense_ ou checagem de valores.
- Bela implementação de Redux com o padrão ducks.
- Boa utilização do _persistStore_ apesar de não precisar ("... outra para listar os repositórios que foram favoritados pelo usuário enquanto ele estiver **com o aplicativo aberto**", ou seja, bastava salvar em memória)
- Bom uso de react-hooks e Stateless components
- Deveria ser possível adicionar/remover dos favoritos ainda na tela de **Trendings** e remover dos favoritos na tela de **Favoritos**. Essas duas funcionalidades só estão disponíveis na tela de **Detalhes** na sua aplicação.
- _Commits_ bem escritos e que explicam bem as alterações feitas no código
- Poderia ter trabalhado um pouco mais nos testes da aplicação, ao menos testes de _snapshots_ em cada um dos componentes com _props_ variadas.
- Você esqueceu de adicionar `SafeAreaView` em suas pages
- Cuidado com a instalação de pacotes se não for utiliza-los (ex.:`react-native-safe-area-context`, `react-native-screens`) , isso aumenta o bundle da sua aplicação desnecessáriamente.

Parabéns pelo projeto, muito bem escrito e apresentado, é uma pena eu não ter conseguido roda-lo. Acredito que você ainda pode melhorar na utilização do `typescript` e `testes`.

**Diferenciais**

- Utilizar Apollo-client
- ~Criar issues e resolvê-las a partir de pull requests~
- Documentação no ~código~ e repositório (Aqui fica uma ressalva, o seu código ficou muito bem escrito, dispensando documentação)
- Arquivos pequenos com poucas responsabilidades
- Estado da aplicação bem estruturado
- ~Usabilidade~ e feedback para o usuário no carregamento da consulta (Não consegui verificar a usabilidade)
- Seguir algum Javascript Style Guide
- ~Utilizar alguma ferramenta de CI~
- ~Testes unitários~

**Comment by neto15cg** [comment]
Bom dia Cássio.
Muito obrigado pelo Feedback.

- Em relação à instalação eu acabei baixando o projeto aqui, eu consegui instalar, o problema em relação ao MACOS foi permissão na pasta android (Na minha máquina).
- A documentação de fato pode ser melhor colocada. (Farei isso).
- Normalmente utilizo typescript, acho que ele ajuda a manter o código limpo e organizado, neste caso específico pelo tempo corrido não implementei os tipos dos dados e acabei utilizando any a contragosto.
- O arquivo de configuração é realmente importante, já que ajuda a futura mudança de paleta de cores.
- Sim o redux de fato não necessitaria. (Um pouco de over engineering).
- Eu percebi que realmente faltava essa possibilidade de adicionar favoritos já na lista, mas acabei ficando preso à interpretação de que seria necessário a colocação do botão de favorito no Detalhe do pacote.
- Em relação ao SafeAreaView, realmente falta, acabei esquecendo, não pude testar em um device IOS por isso passei batido.
- Os pacotes não utilizados de fato é um problema, eu deveria remove-los de fato.
